sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - 1.19.0
  - 1.20.0
  - 1.21.1
  - 1.22.0
  - 1.23.0
  - 1.24.1
  - stable
  - beta

script:
  - cargo build --features timeconversions
  - cargo test  --features timeconversions

cache:
  cargo: true

